<a href="https://colab.research.google.com/github/eathi/Pytorch-codebase/blob/main/Tensor_Mathematical_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [2]:
import torch
import numpy as np

In [6]:
tensor_new_1=torch.arange(10)
tensor_new_1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
tensor_new_2=torch.arange(10)
tensor_new_2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
tensor_new_1+tensor_new_2

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
tensor_new_1-tensor_new_2

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
tensor_new_1*tensor_new_2

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
tensor_new_1/tensor_new_2

tensor([nan, 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
tensor_new_2=tensor_new_2+2

In [22]:
tensor_new_3=tensor_new_2/tensor_new_1
tensor_new_3

tensor([   inf, 3.0000, 2.0000, 1.6667, 1.5000, 1.4000, 1.3333, 1.2857, 1.2500,
        1.2222])

In [23]:
torch.add(tensor_new_1,tensor_new_2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
torch.sub(tensor_new_1,tensor_new_2)

tensor([-2, -2, -2, -2, -2, -2, -2, -2, -2, -2])

In [25]:
torch.mul(tensor_new_1,tensor_new_2)

tensor([ 0,  3,  8, 15, 24, 35, 48, 63, 80, 99])

In [26]:
torch.div(tensor_new_1,tensor_new_2)

tensor([0.0000, 0.3333, 0.5000, 0.6000, 0.6667, 0.7143, 0.7500, 0.7778, 0.8000,
        0.8182])

In [32]:
torch.remainder(tensor_new_1,tensor_new_2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
tensor_new_1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
tensor_new_2=tensor_new_2*3
tensor_new_2

tensor([18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [35]:
tensor_new_1=tensor_new_1+1
tensor_new_1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
torch.remainder(tensor_new_2,tensor_new_1)

tensor([0, 1, 0, 1, 4, 3, 2, 1, 0, 9])

In [38]:
#LONGHAND or power operations like cube square root
torch.pow(tensor_new_2,tensor_new_1)

tensor([                  18,                  729,                46656,
                     4100625,            459165024,          62523502209,
              10030613004288,     1853020188851841,   387420489000000000,
        -1795512867667309079])

In [39]:
tensor_new_2**tensor_new_1

tensor([                  18,                  729,                46656,
                     4100625,            459165024,          62523502209,
              10030613004288,     1853020188851841,   387420489000000000,
        -1795512867667309079])

In [41]:
#LONGHAND for addition
tensor_new_2.add(tensor_new_1)

tensor([ 19,  29,  39,  49,  59,  69,  79,  89,  99, 109])

In [42]:
#LONGHAND for subtraction
tensor_new_2.sub(tensor_new_1)

tensor([17, 25, 33, 41, 49, 57, 65, 73, 81, 89])

In [43]:
#LONGHAND for multiplication
tensor_new_2.mul(tensor_new_1)

tensor([ 18,  54, 108, 180, 270, 378, 504, 648, 810, 990])

In [44]:
#LONGHAND for division
tensor_new_2.div(tensor_new_1)

tensor([18.0000, 13.5000, 12.0000, 11.2500, 10.8000, 10.5000, 10.2857, 10.1250,
        10.0000,  9.9000])

In [40]:
#LONGHAND or power operations like cube square root
tensor_new_2.pow(tensor_new_1)

tensor([                  18,                  729,                46656,
                     4100625,            459165024,          62523502209,
              10030613004288,     1853020188851841,   387420489000000000,
        -1795512867667309079])

In [45]:
#LONGHAND for division
tensor_new_2.remainder(tensor_new_1)

tensor([0, 1, 0, 1, 4, 3, 2, 1, 0, 9])

**REASSIGNMENT OF TENSORS**

Lets say there are two tensors a and b which has to be put through a mathematical operation and save the resulting values to tensor a ;
 * This situation is called re-assigning values  
 * This can be achieved by adding a nderscore to longhand functions in pytorch

For eg: tensor_a.add_(tensor_b)
* tensor_a.sub_(tensor_b)
* tensor_a.mul_(tensor_b)
* tensor_a.div_(tensor_b)
* tensor_a.remainder_(tensor_b)


In [46]:
tensor_a=torch.arange(10)
tensor_a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
tensor_b=torch.arange(10)
tensor_b=tensor_b+1
tensor_b

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
tensor_a.add_(tensor_b)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [49]:
tensor_a

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [50]:
tensor_a.sub_(tensor_b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
tensor_a.mul_(tensor_b)

tensor([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [52]:
tensor_a

tensor([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [54]:
tensor_a.remainder_(tensor_b)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
tensor_b.div_(tensor_a)

RuntimeError: ignored

In [ ]:
#LONGHAND for division
tensor_new_2.remainder(tensor_new_1)