<a href="https://colab.research.google.com/github/eathi/Pytorch-codebase/blob/main/Tensor_Operations_20_11_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

RESHAPE and VIEW similar to numpy array

In [7]:
#reshape
my_tensor=my_tensor.reshape(5,2)
my_tensor

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
#reshape if we don't know the number of items using -1

my_tensor_2=my_tensor.reshape(10,-1)
my_tensor_2

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [12]:
#reshape if we don't know the number of items using -1

my_tensor_2=my_tensor.reshape(-1,10)
my_tensor_2

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
my_tensor_3 = torch.arange(30)
my_tensor_3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
my_tensor_3=my_tensor_3.reshape(-1,10)
my_tensor_3


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
my_tensor_3=my_tensor_3.reshape(10,-1)
my_tensor_3


tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]])

In [16]:
my_tensor_4=torch.arange(30)
my_tensor_4=my_tensor_4.view(10,-1)
my_tensor_4


tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]])

In [18]:
my_tensor_4[9]=3030
my_tensor_4

tensor([[   0,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8],
        [   9,   10,   11],
        [  12,   13,   14],
        [  15,   16,   17],
        [  18,   19,   20],
        [  21,   22,   23],
        [  24,   25,   26],
        [3030, 3030, 3030]])

In [20]:
my_tensor_5=torch.arange(30)
my_tensor_5

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
my_tensor_5[0]=3030
my_tensor_5

tensor([3030,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
          24,   25,   26,   27,   28,   29])

In [23]:
my_tensor_5[29]=2929
my_tensor_5

tensor([3030,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
          24,   25,   26,   27,   28, 2929])

In [25]:
my_tensor_5[29]

tensor(2929)

SLICING A TENSOR

In [26]:
my_tensor_5

tensor([3030,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
          24,   25,   26,   27,   28, 2929])

In [28]:
my_tensor_6=my_tensor_5.reshape(6,5)
my_tensor_6

tensor([[3030,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28, 2929]])

In [36]:
my_tensor_7=my_tensor_6[0:2,0:7]
my_tensor_7

tensor([[3030,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [39]:
my_tensor_8=my_tensor_6[0:,1:]
my_tensor_8

tensor([[   1,    2,    3,    4],
        [   6,    7,    8,    9],
        [  11,   12,   13,   14],
        [  16,   17,   18,   19],
        [  21,   22,   23,   24],
        [  26,   27,   28, 2929]])